- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 2.5h
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  guides: # goobstation
  - Salvage
  - Cargo
  goobcoins: 20 #Goob content
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  special: # Trauma - salv greentext
  - !type:AddObjectiveSpecial
    objectives:
    - SalvageMineObjective

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  storage: # DeltaV: Add mining voucher
    back:
    - MiningVoucher

- type: chameleonOutfit
  id: SalvageSpecialistChameleonOutfit
  job: SalvageSpecialist
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGasExplorer
    outerClothing: ClothingOuterWinterMiner
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesColorBlack
